/*
 * Copyright (c) 2020 The Ontario Institute for Cancer Research. All rights reserved
 *
 * This program and the accompanying materials are made available under the terms of
 * the GNU Affero General Public License v3.0. You should have received a copy of the
 * GNU Affero General Public License along with this program.
 *  If not, see <http://www.gnu.org/licenses/>.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY
 * EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
 * OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED
 * TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
 * OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER
 * IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */
/**
 * FileCentricDocument are the file documents that are indexed in ElasticSearch.
 * They require DB File documents combined with RdpcFileDocuments (generated by the analysisConverter from an RdpcAnalysis)
 *
 * This service is responsible for defining the structure of these FileCentricDocuments and creating them from their source inputs.
 * This differs from the FileManager, which is responsible for managing the state of files in the DB and syncing that state with the ES Indices.
 */

import Logger from '../logger';
import { File } from '../data/files';
import { EmbargoStage, FileReleaseState } from '../data/files';
import { RdpcFileDocument } from '../external/analysisConverter';
const logger = Logger('FileDocumentService');

export type FileCentricDocument = RdpcFileDocument & {
  embargoStage: EmbargoStage;
  releaseState: FileReleaseState;
};

type FileCentricDocumentInputs = {
  dbFile: File;
  rdpcFile: RdpcFileDocument;
};
export const buildDocument = ({
  dbFile,
  rdpcFile: filePartialDocument,
}: FileCentricDocumentInputs): FileCentricDocument => {
  // Confirm we have only a single donor
  if (filePartialDocument.donors.length > 1) {
    logger.warn(
      `FilePartialDocument ${filePartialDocument.fileId} from analysis ${
        filePartialDocument.analysis.analysisId
      } has more than 1 donor: ${filePartialDocument.donors.map(
        (donor: { donorId: string }) => donor.donorId,
      )}`,
    );
  }
  if (!filePartialDocument.donors || filePartialDocument.donors.length < 1) {
    logger.error(`File ${filePartialDocument.fileId} has no associated donors`);
    throw new Error(
      'FileCentricDocument has no donors, it cannot be converted to a FileCentricDocument.',
    );
  }

  // Confirm the file has a fileId
  if (!dbFile.fileId) {
    logger.error(``);
    throw new Error('File record has no fileId, it cannot be converted to a FileCentricDocument.');
  }

  /**
   * Validations done. Work begins:
   */

  const output: FileCentricDocument = {
    ...filePartialDocument,
    fileId: dbFile.fileId,
    embargoStage: dbFile.embargoStage,
    releaseState: dbFile.releaseState,
    meta: {
      embargoStage: dbFile.embargoStage,
      releaseState: dbFile.releaseState,
      studyId: filePartialDocument.studyId,
    },
  };

  return output;
};

export const buildDocuments = (inputs: FileCentricDocumentInputs[]): FileCentricDocument[] =>
  inputs.map(buildDocument);
